version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 10
      
  pre_build: 
     npm install
     
  build:
     npm run build
  
  post_build:
      awss3 sync build/ s3://juusonbucket
