version: 0.2

phases: 
  install:
    runtime-versions:
      nodejs: 10
      
  pre_build:
     commands:
      - npm install
      - aws s3 sync build/ s3://bucketjuuso
     
  build:
    commands:
     - npm run build
  
 
